### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by simply-justin** [madebyfabian/nuxt-calendly#3]
After building nuxt project for production i'm greeted with an ReferenceError: process is not defined error when trying to use the calendly widget. But on development it works perfectly fine.

**Comment by madebyfabian** [comment]
Hi, noticed that error too when using nuxt generate. Fixed it a few days ago, Do you use the latest version?

**Comment by simply-justin** [comment]
Yes, I thought i was but i updated yesterday and everything was working fine! I only forgot to close this issue

**Comment by madebyfabian** [comment]
@Simply-Justin Great to hear 💪
