### ISSUE TITLE
[HELP] How to hide the cookie settings modal

### ISSUE THREAD

**Issue by kusman28** [madebyfabian/nuxt-calendly#5]
I tried to override the CSS 
```
:deep() #onetrust-consent-sdk,
:deep() #onetrust-banner-sdk {
  background-color: red !important;
}
```

and set 
```
pageSettings: {
  hideGdprBanner: true
}
```

![image](https://github.com/madebyfabian/nuxt-calendly/assets/40085614/e7248f24-5122-415a-894b-9124c1f36831)

**Comment by kusman28** [comment]
**Update:**
I was able to fix it by adding this to my calendly URL `/30min?hide_gdpr_banner=1`

**Comment by madebyfabian** [comment]
Great that you found a fix. These things are all handled by calendly and I don't have any impact on it.
