### ISSUE TITLE
Add defineExpose to certain components

### ISSUE THREAD

**Issue by damienmontastier** [madebyfabian/nuxt-calendly#8]
Hey ! 

It is currently not possible to tell from the parent whether a modal is open or not. This is quite restrictive if you want to develop more precise cases. In my case, it would be useful to add: 

```javascript
defineExpose({ isOpen })
```
for example, but we could imagine other values. The components `CalendlyPopupButton`, `CalendlyPopupWidget` seem to be affected.

Thanks !

**Comment by madebyfabian** [comment]
Thanks for noting! I added it in the v0.1.20 release: https://github.com/madebyfabian/nuxt-calendly/releases/tag/v0.1.20 

Sorry it took so long, haven't been recieving notifications for my own repos unfortunately.
